version: 0.1
phases:
    install:
      commands:
        - npm install -g serverless
    build:
      commands:
        - "serverless deploy"
        - "serverless info > service_endpoint.txt"
artifacts:
  files:
    - service_endpoint.txt